name: places
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.13.0-211.6.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.21.0-nullsafety.0
  lorem_cutesum: ^1.0.0
  dio: ^4.0.0
  relation: ^1.0.0
  provider: ^5.0.0
  flutter_mobx: ^2.0.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  flutter_redux: ^0.8.2

dev_dependencies:
  build_runner: ^2.0.1
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3

flutter:
  assets:
    - res/image/
    - res/figma/Icons/
    - res/figma/Icons/Catalog/
    - res/figma/Icons/Catalog/Black/
    - res/figma/Icons/Catalog/White/
    - res/figma/Icons/Icon/
    - res/figma/Icons/tougle/

  uses-material-design: true